### ISSUE TITLE
具体打包部署步骤

### ISSUE THREAD

**Issue by walkwolf** [Zhujinyong/SvnManager#1]
请提供具体打包部署步骤

**Comment by Zhujinyong** [comment]
1、前端页面的打包如下：
npm install
npm run build

2、webapi的打包如下：
可以在windows的vs2017里发布，然后传到linux文件夹下，执行构建镜像，再运行容器；也可以在linux下发布，构建，再运行
dotnet publish -c Release -o out
cd out
docker build --no-cache -t svn-image .
docker run  --name=svn-container -dp  8020:8020 --restart=always  -e LC_ALL="en_US.UTF-8" -e TZ="Asia/Shanghai" svn-image

**Comment by Zhujinyong** [comment]
我已收到您发的邮件，会尽快查看的哦！签名：朱锦勇
